#!/bin/sh
# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Display setup
xrandr --dpi 96
xrandr --output DVI-I-1-1 --mode 1920x1080 --right-of eDP-1

# Wallpaper and theme
dwm_change_theme "${WALLPAPERDIR}/rosahakenkreuz.png" &

# Compositor
picom --config ~/.config/picom/picom.conf &

# Autostart daemons
autostart="dunst pipewire"
for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

nohup dwmblocks >/dev/null 2>&1 &
