console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  color0 = 'black'
  color1 = 'red'
  color10 = 'bright_green'
  color11 = 'bright_yellow'
  color12 = 'bright_blue'
  color13 = 'bright_magenta'
  color14 = 'bright_cyan'
  color15 = 'bright_white'
  color2 = 'green'
  color3 = 'yellow'
  color4 = 'blue'
  color5 = 'magenta'
  color6 = 'cyan'
  color7 = 'white'
  color8 = 'bright_black'
  color9 = 'bright_red'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'foreground'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:color2{{end}}', '{{if eq .Code 0}}p:color9{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' ➜'
    foreground = 'p:color1'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = 'p:color4'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'folder'

  [[blocks.segments]]
    template = ' <p:color4>git:(</>{{ .HEAD }}<p:color4>)</>'
    foreground = 'p:color9'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = '  {{ .Venv }} '
    foreground = 'p:color7'
    background = 'transparent'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'p:color8'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:color9{{end}}', '{{if eq .Code 0}}p:color10{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
